name: Check Store

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-store:
    uses: graycoreio/github-actions-magento2/.github/workflows/check-store.yaml@v8.6.0
    with:
      path: "."
    secrets:
      composer_auth: ${{ secrets.COMPOSER_AUTH }}
